sonar.projectKey=xhrobj-hex_ai-for-developers-project-386
sonar.organization=xhrobj-hex

sonar.sources=backend,frontend
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,frontend/playwright-report/**,frontend/test-results/**
